function [log]=importlog(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/reyes/Google Drive/0_CurrentProjects/NbSe2YIG/160707 NbSe2 on SiO2/S1.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/07 20:02:27

%% Initialize variables.
%filename = '/Users/reyes/Google Drive/0_CurrentProjects/NbSe2YIG/160707 NbSe2 on SiO2/S1.txt';
delimiter = '\t';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%s%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names

log.name = dataArray{:, 3};
log.angle = dataArray{:, 4};
log.Temp = dataArray{:, 5};
log.Hini = dataArray{:, 6};
log.Hfin = dataArray{:, 7};
log.Curr = dataArray{:, 10};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;